#!/bin/bash
cd /opt/

## Extract the package
sudo tar xf /opt/ideaIC-*

## Rename the directory
sudo mv /opt/idea-IC-* /opt/intellij-idea-community

## Remove  the tar.gz package
sudo rm /opt/ideaIC-*

## Make /usr/bin usable
sudo mv /usr/bin/intellij-idea-community.sh /usr/bin/intellij-idea-community
