#!/bin/bash

set -e

## Remove the program folder
sudo rm -rf /opt/intellij-idea-community

## Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/intellij-idea-ce.png
fi
# End automatically added section
#
