#!/bin/bash

set -e

cd /opt/

## Extract the package
sudo tar xf /opt/ideaIC-*

## Rename the directory
sudo mv /opt/idea-IC-* /opt/intellij-idea-community

## Remove  the tar.gz package
sudo rm /opt/ideaIC-*

## Install the .desktop file, if necessary
if [ -x "/usr/bin/desktop-file-install" ]; then
    sudo desktop-file-install /usr/share/applications/intellij-idea-community.desktop
fi

## Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/intellij-idea-ce.png
fi
# End automatically added section
#
