#!/bin/bash

set -e

cd /opt/

## Extract the package
tar xf /opt/ideaIC-2025.2.tar.gz

## Rename the directory
mv /opt/idea-IC-* /opt/intellij-idea-community

## Remove  the tar.gz package
rm /opt/ideaIC-2025.2.tar.gz

## Install the .desktop file, if necessary
if [ -x "/usr/bin/desktop-file-install" ]; then
    desktop-file-install /usr/share/applications/intellij-idea-community.desktop
fi

##DEBHELPER##
