#!/bin/bash

set -e

cd /opt/

## Extract the package
sudo tar xf /opt/ideaIC-*

## Rename the directory
sudo mv /opt/idea-IC-* /opt/intellij-idea-community

## Remove  the tar.gz package
sudo rm /opt/ideaIC-*

## Install the .desktop file, if necessary
if [ -x "/usr/bin/desktop-file-install" ]; then
    sudo desktop-file-install /usr/share/applications/intellij-idea-community.desktop
fi

## Switch to new repository, if necessary
oldrepo="mmk2410\/intellij-idea-community"
newrepo="mmk2410\/intellij-idea"
grep -rl "$oldrepo" /etc/apt/sources.list | xargs -r sed -i "s/$oldrepo/$newrepo/g"
grep -rl "$oldrepo" /etc/apt/sources.list.d/ | xargs -r sed -i "s/$oldrepo/$newrepo/g"

##DEBHELPER##
