#!/bin/bash

set -e

cd /opt/

## Extract the package
sudo tar xf /opt/ideaIC-2021.2.2.tar.gz

## Rename the directory
sudo mv /opt/idea-IC-* /opt/intellij-idea-community

## Remove  the tar.gz package
sudo rm /opt/ideaIC-2021.2.2.tar.gz

## Install the .desktop file, if necessary
if [ -x "/usr/bin/desktop-file-install" ]; then
    sudo desktop-file-install /usr/share/applications/intellij-idea-community.desktop
fi

##DEBHELPER##
